# Generated by Django 6.0 on 2026-01-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., WhatsApp, LinkedIn, Facebook', max_length=50)),
                ('url', models.URLField(help_text='Full link to your profile or contact')),
                ('icon', models.CharField(help_text="Use an emoji or font-awesome class like 'fab fa-linkedin'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
