# Generated by Django 6.0 on 2026-01-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_github_url_project_live_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order'], 'verbose_name': 'Timeline Event', 'verbose_name_plural': 'Timeline Events'},
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(default='', help_text='One feature per line (shown as bullet points)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='', help_text='Comma separated e.g. Django, JavaScript, PostgreSQL', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='💻', help_text='Use an emoji or font-awesome class for icon', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='Enter a number 0-100 for skill level'),
        ),
    ]
