# Generated by Django 6.0 on 2026-01-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_education_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.TextField(default='', help_text='One feature per line (shown as bullet points)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='', help_text='Comma separated e.g. Django, JavaScript, PostgreSQL', max_length=255),
        ),
    ]
