# Generated by Django 6.0 on 2026-01-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_project_features_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.CharField(blank=True, help_text='Static path e.g., images/about.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.CharField(help_text='Static path e.g., images/hero1.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.TextField(help_text='One feature per line (shown as bullet points)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(help_text='Static path e.g., images/project1.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma separated e.g. Django, JavaScript, PostgreSQL', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='💻', help_text='Static path or emoji, e.g., images/service_icon.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Static path e.g., images/skill_icon.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(help_text='Static path, emoji, or font-awesome class', max_length=255),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='icon',
            field=models.CharField(blank=True, help_text='Static path e.g., images/timeline_icon.png', max_length=255, null=True),
        ),
    ]
