# Generated by Django 6.0 on 2026-01-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactmessage_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
